# -*- coding: utf-8 -*-
"""Copy of Training YOLOR on a Custom Dataset.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K6WRPgb8PIpfIGua5V7orWsv_8ecq2V7

# How to Train YOLOR on Custom Objects

This tutorial is based on the [YOLOR repository](https://github.com/WongKinYiu/yolor) by [Wong Kin-Yiu](https://github.com/WongKinYiu). This notebook shows training on **your own custom objects**. Many thanks to Wong for putting this repository together - we hope that in combination with clean data management tools at Roboflow, this technologoy will become easily accessible to any developer wishing to use computer vision in their projects.

### Accompanying Blog Post

We recommend that you follow along in this notebook while reading the blog post on [How to Train YOLOR](blog.roboflow.com/how-to-train-yolor-on-a-custom-dataset/), concurrently.

### Steps Covered in this Tutorial

In this tutorial, we will walk through the steps required to train YOLOR on your custom objects. We use a [public blood cell detection dataset](https://public.roboflow.ai/object-detection/bccd), which is open source and free to use. You can also use this notebook on your own data.

To train our detector we take the following steps:

* Install YOLOR dependencies
* Download custom YOLOR object detection data
* Prepare Pre-Trained Weights for YOLOR
* Run YOLOR training
* Evaluate YOLOR performance
* Visualize YOLOR training data
* Run YOLOR inference on test images
* Export saved YOLOR weights for future inference

### **About**

[Roboflow](https://roboflow.com) enables teams to deploy custom computer vision models quickly and accurately. Convert data from to annotation format, assess dataset health, preprocess, augment, and more. It's free for your first 1000 source images.

**Looking for a vision model available via API without hassle? Try Roboflow Train.**

![Roboflow Wordmark](https://i.imgur.com/dcLNMhV.png)

#Install Dependencies

_(Remember to choose GPU in Runtime if not already selected. Runtime --> Change Runtime Type --> Hardware accelerator --> GPU)_
"""

# Commented out IPython magic to ensure Python compatibility.
# clone YOLOR repository
!git clone https://github.com/roboflow-ai/yolor
# %cd yolor
!git reset --hard eb3ef0b7472413d6740f5cde39beb1a2f5b8b5d1

# Install necessary dependencies
!pip install -r requirements.txt
# conda install --file requirements.txt

# Commented out IPython magic to ensure Python compatibility.
# Install Mish CUDA
!git clone https://github.com/JunnYu/mish-cuda
# %cd mish-cuda
!git reset --hard 6f38976064cbcc4782f4212d7c0c5f6dd5e315a8
!python setup.py build install
# %cd ..

# Commented out IPython magic to ensure Python compatibility.
# Install PyTorch Wavelets
!git clone https://github.com/fbcotter/pytorch_wavelets
# %cd pytorch_wavelets
!pip install .
# %cd ..

"""# Download Correctly Formatted Custom Dataset 

We'll download our dataset from Roboflow. Use the "**YOLOv5 PyTorch**" export format. Note that the Ultralytics implementation calls for a YAML file defining where your training and test data is. The Roboflow export also writes this format for us.

To get your data into Roboflow, follow the [Getting Started Guide](https://blog.roboflow.ai/getting-started-with-roboflow/).

![YOLOv5 PyTorch export](https://i.imgur.com/5vr9G2u.png)

"""


# !pip install roboflow
from roboflow import Roboflow
rf = Roboflow(api_key="j5T2cCGBbriYBlLyNw5I")
project = rf.workspace("drago1234").project("zero-waste")
dataset = project.version(1).download("yolov5")

# For Yolo v4 PyTorch
from roboflow import Roboflow
rf = Roboflow(api_key="j5T2cCGBbriYBlLyNw5I")
project = rf.workspace("drago1234").project("zero-waste")
dataset = project.version(1).download("yolov4pytorch")

# For Scaled Yolo-V4
from roboflow import Roboflow
rf = Roboflow(api_key="j5T2cCGBbriYBlLyNw5I")
project = rf.workspace("drago1234").project("zero-waste")
dataset = project.version(1).download("yolov4scaled")


# this is the YAML file Roboflow wrote for us that we're loading into this notebook with our data
%cat ./zero-waste-1/data.yaml

"""# Prepare Pre-Trained Weights for YOLOR"""
%cd yolor
!bash scripts/get_pretrain.sh	# Dowloading pre-trained weight for yolor
# ==> This doesn't work, just download them manually and upload to the project folder.
# curl -c ./cookie -s -L "https://drive.google.com/uc?export=download&id=1Tdn3yqpZ79X7R1Ql0zNlNScB1Dv9Fp76" > /dev/null
# curl -c ./cookie -s -L "https://drive.google.com/uc?export=download&id=1UflcHlN5ERPdhahMivQYCbWWw7d2wY7U" > /dev/null

"""# Write YOLOR Configuration"""
import yaml
with open('./zero-waste-1/' + "data.yaml") as f:
    dataMap = yaml.safe_load(f)

num_classes = len(dataMap['names'])
num_filters = (num_classes + 5) * 3
from IPython.core.magic import register_line_cell_magic

@register_line_cell_magic
def writetemplate(line, cell):
    with open(line, 'w') as f:
        f.write(cell.format(**globals()))

# See the configuration file
%cat ./cfg/yolor_p6.cfg


"""# Train Custom YOLOR Detector
### Next, we'll fire off training!

Here, we are able to pass a number of arguments:
- **img:** define input image size
- **batch:** determine batch size
- **epochs:** define the number of training epochs. (Note: often, 3000+ are common here!)
- **data:** set the path to our yaml file
- **cfg:** specify our model configuration
- **weights:** specify a custom path to weights. (Note: We can specify the pretrained weights we downloaded up above with the shell script)
- **name:** result names
-**hyp:** Define the hyperparamters for training
"""

# Start the training
%cd /content/yolor
# !python train.py --batch-size 8 --img 416 416 --data {dataset.location}/data.yaml --cfg cfg/yolor_p6.cfg --weights '/content/yolor/yolor_p6.pt' --device 0 --name yolor_p6 --hyp '/content/yolor/data/hyp.scratch.1280.yaml' --epochs 50
# Assume you are in the roboflow folder
# Running for yolor
# python ./yolor/train.py --batch-size 8 --img 416 416 --data ./zero-waste-1/data.yaml --cfg ./yolor/cfg/yolor_p6.cfg --weights './yolor/weights/yolor_p6.pt' --device 0 --name yolor_p6 --hyp './yolor/data/hyp.scratch.1280.yaml' --epochs 1
# Running for Yolov4
# python ./yolor/train.py --batch-size 8 --img 416 416 --data ./zero-waste-1/data.yaml --cfg ./yolor/cfg/yolov4_csp_x.cfg --weights './yolor/weights/yolov4.weights' --device 0 --name yolov4 --hyp './yolor/data/hyp.scratch.1280.yaml' --epochs 1


"""# Evaluate Custom YOLOR Detector Performance

Training losses and performance metrics are saved to Tensorboard and also to a logfile defined above with the **--name** flag when we train. In our case, we named this `yolor_p6`. (If given no name, it defaults to `results.txt`.) The results file is plotted as a png after training completes.
"""
# Evaluate Custom YOLOR Detector Performance with TensorBoard
# Start tensorboard
# Launch after you have started training
# logs save in the folder "runs"
%load_ext tensorboard
%tensorboard --logdir runs

from IPython.display import Image
# we can also output some older school graphs if the tensor board isn't working for whatever reason... 
from utils.plots import plot_results  # plot results.txt as results.png
Image(filename='/content/yolor/runs/train/yolor_p6/results.png', width=1000)  # view results.png

# first, display our ground truth data
print("GROUND TRUTH TRAINING DATA:")
Image(filename='/content/yolor/runs/train/yolor_p6/train_batch0.jpg', width=900)

print("AUGMENTED DATA:")
Image(filename='/content/yolor/runs/train/yolor_p6/train_batch0.jpg', width=900)

"""#Run Inference  With Trained Weights
Run inference with a pretrained checkpoint on contents of `test/images` folder downloaded from Roboflow.
"""
# trained weights are saved by default in our weights folder
%ls runs/   
%ls runs/train/yolor_p6/weights # showing all the weight file .pt

# Create names file for model
import yaml
import ast
with open("../data.yaml", 'r') as stream:
    names = str(yaml.safe_load(stream)['names'])

namesFile = open("../data.names", "w+")
names = ast.literal_eval(names)
for name in names:
  namesFile.write(name +'\n')
namesFile.close()

!python yolor/detect.py --weights "runs/train/yolor_p64/weights/best_overall.pt" --conf 0.5 --source zero-waste-1/test/images --names yolor/data/zerowaste.names --cfg yolor/cfg/yolor_p6.cfg

#display inference on ALL test images
#this looks much better with longer training above

import glob
from IPython.display import Image, display

for imageName in glob.glob('/content/yolor/inference/output/*.jpg'): #assuming JPG
    display(Image(filename=imageName))
    print("\n")


## Export training weights for Future Inference
# Now that you have trained your custom detector, you can export the trained weights you have made here for inference on your device elsewhere
from google.colab import drive
drive.mount('/content/gdrive')

%cp /content/yolor/runs/train/yolor_p6/weights/best.pt /content/gdrive/My\ Drive

# Reference:
# https://colab.research.google.com/drive/1e1Uk9SjxBaagu7aoGZ4oTcqePhnMLM23?usp=sharing#scrollTo=dQrUGu9nYI-T

"""## Congrats!

Hope you enjoyed this!

--Team [Roboflow](https://roboflow.ai)
"""